# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LinearRegression.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import MPCInput_pb2 as MPCInput__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LinearRegression.proto',
  package='dk.alexandra.fresco.service.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16LinearRegression.proto\x12$dk.alexandra.fresco.service.messages\x1a\x0eMPCInput.proto\"\x8f\x01\n\x15LinearRegressionInput\x12:\n\x01x\x18\x01 \x03(\x0b\x32/.dk.alexandra.fresco.service.messages.MPCVector\x12:\n\x01y\x18\x02 \x01(\x0b\x32/.dk.alexandra.fresco.service.messages.MPCVector\"&\n\x16LinearRegressionOutput\x12\x0c\n\x04\x62\x65ta\x18\x01 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[MPCInput__pb2.DESCRIPTOR,])




_LINEARREGRESSIONINPUT = _descriptor.Descriptor(
  name='LinearRegressionInput',
  full_name='dk.alexandra.fresco.service.messages.LinearRegressionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='dk.alexandra.fresco.service.messages.LinearRegressionInput.x', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='dk.alexandra.fresco.service.messages.LinearRegressionInput.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=224,
)


_LINEARREGRESSIONOUTPUT = _descriptor.Descriptor(
  name='LinearRegressionOutput',
  full_name='dk.alexandra.fresco.service.messages.LinearRegressionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='beta', full_name='dk.alexandra.fresco.service.messages.LinearRegressionOutput.beta', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=264,
)

_LINEARREGRESSIONINPUT.fields_by_name['x'].message_type = MPCInput__pb2._MPCVECTOR
_LINEARREGRESSIONINPUT.fields_by_name['y'].message_type = MPCInput__pb2._MPCVECTOR
DESCRIPTOR.message_types_by_name['LinearRegressionInput'] = _LINEARREGRESSIONINPUT
DESCRIPTOR.message_types_by_name['LinearRegressionOutput'] = _LINEARREGRESSIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LinearRegressionInput = _reflection.GeneratedProtocolMessageType('LinearRegressionInput', (_message.Message,), {
  'DESCRIPTOR' : _LINEARREGRESSIONINPUT,
  '__module__' : 'LinearRegression_pb2'
  # @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.LinearRegressionInput)
  })
_sym_db.RegisterMessage(LinearRegressionInput)

LinearRegressionOutput = _reflection.GeneratedProtocolMessageType('LinearRegressionOutput', (_message.Message,), {
  'DESCRIPTOR' : _LINEARREGRESSIONOUTPUT,
  '__module__' : 'LinearRegression_pb2'
  # @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.LinearRegressionOutput)
  })
_sym_db.RegisterMessage(LinearRegressionOutput)


# @@protoc_insertion_point(module_scope)
