# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TTest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import MPCInput_pb2 as MPCInput__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TTest.proto',
  package='dk.alexandra.fresco.service.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bTTest.proto\x12$dk.alexandra.fresco.service.messages\x1a\x0eMPCInput.proto\"\x84\x01\n\nTTestInput\x12:\n\x01x\x18\x01 \x01(\x0b\x32/.dk.alexandra.fresco.service.messages.MPCVector\x12:\n\x01y\x18\x02 \x01(\x0b\x32/.dk.alexandra.fresco.service.messages.MPCVector\"\x18\n\x0bTTestOutput\x12\t\n\x01t\x18\x01 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[MPCInput__pb2.DESCRIPTOR,])




_TTESTINPUT = _descriptor.Descriptor(
  name='TTestInput',
  full_name='dk.alexandra.fresco.service.messages.TTestInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='dk.alexandra.fresco.service.messages.TTestInput.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='dk.alexandra.fresco.service.messages.TTestInput.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=202,
)


_TTESTOUTPUT = _descriptor.Descriptor(
  name='TTestOutput',
  full_name='dk.alexandra.fresco.service.messages.TTestOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='dk.alexandra.fresco.service.messages.TTestOutput.t', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=228,
)

_TTESTINPUT.fields_by_name['x'].message_type = MPCInput__pb2._MPCVECTOR
_TTESTINPUT.fields_by_name['y'].message_type = MPCInput__pb2._MPCVECTOR
DESCRIPTOR.message_types_by_name['TTestInput'] = _TTESTINPUT
DESCRIPTOR.message_types_by_name['TTestOutput'] = _TTESTOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TTestInput = _reflection.GeneratedProtocolMessageType('TTestInput', (_message.Message,), {
  'DESCRIPTOR' : _TTESTINPUT,
  '__module__' : 'TTest_pb2'
  # @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.TTestInput)
  })
_sym_db.RegisterMessage(TTestInput)

TTestOutput = _reflection.GeneratedProtocolMessageType('TTestOutput', (_message.Message,), {
  'DESCRIPTOR' : _TTESTOUTPUT,
  '__module__' : 'TTest_pb2'
  # @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.TTestOutput)
  })
_sym_db.RegisterMessage(TTestOutput)


# @@protoc_insertion_point(module_scope)
