// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTest.proto

package dk.alexandra.fresco.service.messages;

public final class TTest {
  private TTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TTestInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.alexandra.fresco.service.messages.TTestInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     * @return The x.
     */
    dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getX();
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     */
    dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getXOrBuilder();

    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     * @return The y.
     */
    dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getY();
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     */
    dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getYOrBuilder();
  }
  /**
   * Protobuf type {@code dk.alexandra.fresco.service.messages.TTestInput}
   */
  public static final class TTestInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.alexandra.fresco.service.messages.TTestInput)
      TTestInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TTestInput.newBuilder() to construct.
    private TTestInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TTestInput() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TTestInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TTestInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder subBuilder = null;
              if (x_ != null) {
                subBuilder = x_.toBuilder();
              }
              x_ = input.readMessage(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(x_);
                x_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder subBuilder = null;
              if (y_ != null) {
                subBuilder = y_.toBuilder();
              }
              y_ = input.readMessage(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(y_);
                y_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.alexandra.fresco.service.messages.TTest.TTestInput.class, dk.alexandra.fresco.service.messages.TTest.TTestInput.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector x_;
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return x_ != null;
    }
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getX() {
      return x_ == null ? dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : x_;
    }
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
     */
    @java.lang.Override
    public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getXOrBuilder() {
      return getX();
    }

    public static final int Y_FIELD_NUMBER = 2;
    private dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector y_;
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return y_ != null;
    }
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getY() {
      return y_ == null ? dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : y_;
    }
    /**
     * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
     */
    @java.lang.Override
    public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getYOrBuilder() {
      return getY();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != null) {
        output.writeMessage(1, getX());
      }
      if (y_ != null) {
        output.writeMessage(2, getY());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getX());
      }
      if (y_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getY());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.alexandra.fresco.service.messages.TTest.TTestInput)) {
        return super.equals(obj);
      }
      dk.alexandra.fresco.service.messages.TTest.TTestInput other = (dk.alexandra.fresco.service.messages.TTest.TTestInput) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (!getX()
            .equals(other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (!getY()
            .equals(other.getY())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getX().hashCode();
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getY().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.alexandra.fresco.service.messages.TTest.TTestInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.alexandra.fresco.service.messages.TTestInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.alexandra.fresco.service.messages.TTestInput)
        dk.alexandra.fresco.service.messages.TTest.TTestInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.alexandra.fresco.service.messages.TTest.TTestInput.class, dk.alexandra.fresco.service.messages.TTest.TTestInput.Builder.class);
      }

      // Construct using dk.alexandra.fresco.service.messages.TTest.TTestInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (xBuilder_ == null) {
          x_ = null;
        } else {
          x_ = null;
          xBuilder_ = null;
        }
        if (yBuilder_ == null) {
          y_ = null;
        } else {
          y_ = null;
          yBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor;
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestInput getDefaultInstanceForType() {
        return dk.alexandra.fresco.service.messages.TTest.TTestInput.getDefaultInstance();
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestInput build() {
        dk.alexandra.fresco.service.messages.TTest.TTestInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestInput buildPartial() {
        dk.alexandra.fresco.service.messages.TTest.TTestInput result = new dk.alexandra.fresco.service.messages.TTest.TTestInput(this);
        if (xBuilder_ == null) {
          result.x_ = x_;
        } else {
          result.x_ = xBuilder_.build();
        }
        if (yBuilder_ == null) {
          result.y_ = y_;
        } else {
          result.y_ = yBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.alexandra.fresco.service.messages.TTest.TTestInput) {
          return mergeFrom((dk.alexandra.fresco.service.messages.TTest.TTestInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.alexandra.fresco.service.messages.TTest.TTestInput other) {
        if (other == dk.alexandra.fresco.service.messages.TTest.TTestInput.getDefaultInstance()) return this;
        if (other.hasX()) {
          mergeX(other.getX());
        }
        if (other.hasY()) {
          mergeY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.alexandra.fresco.service.messages.TTest.TTestInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.alexandra.fresco.service.messages.TTest.TTestInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector x_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder> xBuilder_;
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       * @return Whether the x field is set.
       */
      public boolean hasX() {
        return xBuilder_ != null || x_ != null;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       * @return The x.
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getX() {
        if (xBuilder_ == null) {
          return x_ == null ? dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : x_;
        } else {
          return xBuilder_.getMessage();
        }
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public Builder setX(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector value) {
        if (xBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          x_ = value;
          onChanged();
        } else {
          xBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public Builder setX(
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder builderForValue) {
        if (xBuilder_ == null) {
          x_ = builderForValue.build();
          onChanged();
        } else {
          xBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public Builder mergeX(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector value) {
        if (xBuilder_ == null) {
          if (x_ != null) {
            x_ =
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.newBuilder(x_).mergeFrom(value).buildPartial();
          } else {
            x_ = value;
          }
          onChanged();
        } else {
          xBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public Builder clearX() {
        if (xBuilder_ == null) {
          x_ = null;
          onChanged();
        } else {
          x_ = null;
          xBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder getXBuilder() {
        
        onChanged();
        return getXFieldBuilder().getBuilder();
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getXOrBuilder() {
        if (xBuilder_ != null) {
          return xBuilder_.getMessageOrBuilder();
        } else {
          return x_ == null ?
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : x_;
        }
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector x = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder> 
          getXFieldBuilder() {
        if (xBuilder_ == null) {
          xBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder>(
                  getX(),
                  getParentForChildren(),
                  isClean());
          x_ = null;
        }
        return xBuilder_;
      }

      private dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector y_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder> yBuilder_;
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       * @return Whether the y field is set.
       */
      public boolean hasY() {
        return yBuilder_ != null || y_ != null;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       * @return The y.
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector getY() {
        if (yBuilder_ == null) {
          return y_ == null ? dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : y_;
        } else {
          return yBuilder_.getMessage();
        }
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public Builder setY(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector value) {
        if (yBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          y_ = value;
          onChanged();
        } else {
          yBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public Builder setY(
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder builderForValue) {
        if (yBuilder_ == null) {
          y_ = builderForValue.build();
          onChanged();
        } else {
          yBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public Builder mergeY(dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector value) {
        if (yBuilder_ == null) {
          if (y_ != null) {
            y_ =
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.newBuilder(y_).mergeFrom(value).buildPartial();
          } else {
            y_ = value;
          }
          onChanged();
        } else {
          yBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public Builder clearY() {
        if (yBuilder_ == null) {
          y_ = null;
          onChanged();
        } else {
          y_ = null;
          yBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder getYBuilder() {
        
        onChanged();
        return getYFieldBuilder().getBuilder();
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      public dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder getYOrBuilder() {
        if (yBuilder_ != null) {
          return yBuilder_.getMessageOrBuilder();
        } else {
          return y_ == null ?
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.getDefaultInstance() : y_;
        }
      }
      /**
       * <code>.dk.alexandra.fresco.service.messages.MPCVector y = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder> 
          getYFieldBuilder() {
        if (yBuilder_ == null) {
          yBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVector.Builder, dk.alexandra.fresco.service.messages.MPCInputOuterClass.MPCVectorOrBuilder>(
                  getY(),
                  getParentForChildren(),
                  isClean());
          y_ = null;
        }
        return yBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.alexandra.fresco.service.messages.TTestInput)
    }

    // @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.TTestInput)
    private static final dk.alexandra.fresco.service.messages.TTest.TTestInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.alexandra.fresco.service.messages.TTest.TTestInput();
    }

    public static dk.alexandra.fresco.service.messages.TTest.TTestInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TTestInput>
        PARSER = new com.google.protobuf.AbstractParser<TTestInput>() {
      @java.lang.Override
      public TTestInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TTestInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TTestInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TTestInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.alexandra.fresco.service.messages.TTest.TTestInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TTestOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.alexandra.fresco.service.messages.TTestOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double t = 1;</code>
     * @return The t.
     */
    double getT();
  }
  /**
   * Protobuf type {@code dk.alexandra.fresco.service.messages.TTestOutput}
   */
  public static final class TTestOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.alexandra.fresco.service.messages.TTestOutput)
      TTestOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TTestOutput.newBuilder() to construct.
    private TTestOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TTestOutput() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TTestOutput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TTestOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              t_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.alexandra.fresco.service.messages.TTest.TTestOutput.class, dk.alexandra.fresco.service.messages.TTest.TTestOutput.Builder.class);
    }

    public static final int T_FIELD_NUMBER = 1;
    private double t_;
    /**
     * <code>double t = 1;</code>
     * @return The t.
     */
    @java.lang.Override
    public double getT() {
      return t_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (t_ != 0D) {
        output.writeDouble(1, t_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (t_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, t_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.alexandra.fresco.service.messages.TTest.TTestOutput)) {
        return super.equals(obj);
      }
      dk.alexandra.fresco.service.messages.TTest.TTestOutput other = (dk.alexandra.fresco.service.messages.TTest.TTestOutput) obj;

      if (java.lang.Double.doubleToLongBits(getT())
          != java.lang.Double.doubleToLongBits(
              other.getT())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getT()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.alexandra.fresco.service.messages.TTest.TTestOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.alexandra.fresco.service.messages.TTestOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.alexandra.fresco.service.messages.TTestOutput)
        dk.alexandra.fresco.service.messages.TTest.TTestOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.alexandra.fresco.service.messages.TTest.TTestOutput.class, dk.alexandra.fresco.service.messages.TTest.TTestOutput.Builder.class);
      }

      // Construct using dk.alexandra.fresco.service.messages.TTest.TTestOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        t_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.alexandra.fresco.service.messages.TTest.internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor;
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestOutput getDefaultInstanceForType() {
        return dk.alexandra.fresco.service.messages.TTest.TTestOutput.getDefaultInstance();
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestOutput build() {
        dk.alexandra.fresco.service.messages.TTest.TTestOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.alexandra.fresco.service.messages.TTest.TTestOutput buildPartial() {
        dk.alexandra.fresco.service.messages.TTest.TTestOutput result = new dk.alexandra.fresco.service.messages.TTest.TTestOutput(this);
        result.t_ = t_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.alexandra.fresco.service.messages.TTest.TTestOutput) {
          return mergeFrom((dk.alexandra.fresco.service.messages.TTest.TTestOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.alexandra.fresco.service.messages.TTest.TTestOutput other) {
        if (other == dk.alexandra.fresco.service.messages.TTest.TTestOutput.getDefaultInstance()) return this;
        if (other.getT() != 0D) {
          setT(other.getT());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.alexandra.fresco.service.messages.TTest.TTestOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.alexandra.fresco.service.messages.TTest.TTestOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double t_ ;
      /**
       * <code>double t = 1;</code>
       * @return The t.
       */
      @java.lang.Override
      public double getT() {
        return t_;
      }
      /**
       * <code>double t = 1;</code>
       * @param value The t to set.
       * @return This builder for chaining.
       */
      public Builder setT(double value) {
        
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double t = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearT() {
        
        t_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.alexandra.fresco.service.messages.TTestOutput)
    }

    // @@protoc_insertion_point(class_scope:dk.alexandra.fresco.service.messages.TTestOutput)
    private static final dk.alexandra.fresco.service.messages.TTest.TTestOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.alexandra.fresco.service.messages.TTest.TTestOutput();
    }

    public static dk.alexandra.fresco.service.messages.TTest.TTestOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TTestOutput>
        PARSER = new com.google.protobuf.AbstractParser<TTestOutput>() {
      @java.lang.Override
      public TTestOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TTestOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TTestOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TTestOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.alexandra.fresco.service.messages.TTest.TTestOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_alexandra_fresco_service_messages_TTestInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_alexandra_fresco_service_messages_TTestOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013TTest.proto\022$dk.alexandra.fresco.servi" +
      "ce.messages\032\016MPCInput.proto\"\204\001\n\nTTestInp" +
      "ut\022:\n\001x\030\001 \001(\0132/.dk.alexandra.fresco.serv" +
      "ice.messages.MPCVector\022:\n\001y\030\002 \001(\0132/.dk.a" +
      "lexandra.fresco.service.messages.MPCVect" +
      "or\"\030\n\013TTestOutput\022\t\n\001t\030\001 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dk.alexandra.fresco.service.messages.MPCInputOuterClass.getDescriptor(),
        });
    internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_alexandra_fresco_service_messages_TTestInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_alexandra_fresco_service_messages_TTestInput_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_alexandra_fresco_service_messages_TTestOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_alexandra_fresco_service_messages_TTestOutput_descriptor,
        new java.lang.String[] { "T", });
    dk.alexandra.fresco.service.messages.MPCInputOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
